steps:
    - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/firecrawl', '.']
    dir: 'firecrawl'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/firecrawl', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/firecrawl']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - firecrawl
      - --image=gcr.io/$PROJECT_ID/firecrawl
      - --platform=managed
      - --region=asia-southeast1
      - --allow-unauthenticated
      - --port=8080

images:
  - gcr.io/$PROJECT_ID/firecrawl
